name: Deploy to Railway (Staging)

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Trigger Railway deployment
        run: railway deploy --service 843606fb-081b-4c83-b572-72e581f5f593
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}